[workspace]
members = ["core-cli", "gui-base"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
tokio = { version = "1.35", features = ["full"] }
anyhow = "1.0"
ignore = "0.4"
walkdir = "2.4"
flume = "0.11"
