[package]
name = "lala"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.28"
egui = "0.28"
pulldown-cmark = "0.11"

[dev-dependencies]

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
lto = true
